### PR TITLE
Update GCC to 4.9

### PR DESCRIPTION
**Pull request by astapleton**
The bottle will be out of date after this change...

### CODE REVIEW

**Comment by astapleton** [comment]
Compiled version with compilation from previous version did not successfully compile the tintin repo

**Comment by kevincon** [comment]
Even if GDB with python is included by default, which python does it use (e.g. Homebrew vs. OSX built-in)? Could we still expose the option to the user like before so that they can specify it?

**Comment by corhere** [comment]
The prebuilt `arm-none-eabi-gdb-py` uses the system Python.

**Comment by kevincon** [comment]
I talked to Andrew offline, my concern was running into issues with Python package dependencies that our GDB Python scripts use (my reason for adding the `--with-brewed-python` flag was because of this issue where the OSX Python wasn't working for me but the Homebrew Python did), but he showed me on his computer that the commands I usually use seem to work without issues, so I'm fine with it. 🚢  it

**Comment by kevincon** [comment]
I actually tried installing the formula (after uninstalling my existing `arm-none-eabi-gcc` package), and sure enough I run into some issues with running `./waf qemu_gdb`:

```
➜  tintin git:(master) ./waf qemu_gdb
Waf: Entering directory `/Users/kevinconley/pebble-dev/tintin/build'
INFO:root:Connecting to target system on localhost:1234
INFO:root:Connected to target system on localhost:1234
GNU gdb (GNU Tools for ARM Embedded Processors) 7.8.0.20150604-cvs
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=x86_64-apple-darwin10 --target=arm-none-eabi".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
/Users/kevinconley/.gdbinit:16: Error in sourced command file:
�:16: Error in sourced command file:
Undefined command: "import".  Try "help".
Reading symbols from build/src/fw/tintin_fw.elf...done.
.gdbinit:4: Error in sourced command file:
collections:16: Error in sourced command file:
Undefined command: "import".  Try "help".
Remote debugging using :1233
Remote connection closed
(gdb)
```

The error comes about from my .gdbinit file trying to `source /Users/kevinconley/pebble-dev/tintin/tools/gdb_scripts/gdb_tintin.py`.

@astapleton what does your .gdbinit file look like? Maybe I just need to fix my .gdbinit file to make things work.

**Comment by corhere** [comment]
The Python-enabled GDB is installed as `arm-none-eabi-gdb-py`, which is not what `./waf gdb` and friends invokes.

**Comment by kevincon** [comment]
So to sum it up, I think where we're at is: 
- Francois will make Bamboo use gcc 4.9 today
- But we won’t force everyone to upgrade to gcc 4.9 yet because actually 4.8 will still work
- But we should spend time figuring out how to fix the homebrew formula so that it can compile from source

Andrew had also suggested that we change `./waf gdb` to use the right binary, but @franc0is pointed out that `./waf gdb` isn't the only part of waf that specifies which GDB to use, or something like that, so it's more complicated than just changing it in one place.

**Comment by bradtgmurray** [comment]
Should we symlink arm-none-eabi-gdb to point to arm-none-eabi-py?

**Comment by astapleton** [comment]
I can look into that. Do we still need to compile from source? I'm not sure why that is necessary?

**Comment by astapleton** [comment]
Hmm, the other issue is that it uses system python. It might be possible to force it to use brewed python. I guess that is the reason we were compiling from source?

**Comment by bgomberg** [comment]
I pushed a change which will cause this recipe to create "arm-none-eabi-gdb" which includes python support, and "arm-none-eabi-gdb-no-py" which doesn't.

**Comment by bradtgmurray** [comment]
:+1:

**Comment by astapleton** [comment]
🚢 it

**Pull request merged**
